FROM node:23-alpine

WORKDIR /app

# outils de compilation (nécessaire pour bcrypt) && installation nodemon
RUN apk add --no-cache g++ gcc make python3

COPY package*.json ./

# Installer toutes les dépendances
RUN npm install --production

COPY . .

EXPOSE 3001

CMD ["npm", "start"]