FROM node:23-alpine

# WORKDIR /api
WORKDIR /app

# outils de compilation (nécessaire pour bcrypt) && installation nodemon
RUN apk add --no-cache g++ gcc make python3 && npm install -g nodemon 

COPY package*.json ./

# Installer toutes les dépendances
RUN npm install --production

COPY . .

EXPOSE 3001

# CMD ["nodemon", "--config", "nodemon.json"]
CMD ["npm", "run", "dev"]